### ISSUE TITLE
Cannot use this library alongside JFoenix extended POJO's 

### ISSUE THREAD

**Issue by skorper** [joffrey-bion/fx-gson#6] opened 2016-11-02 22:54 UTC
really like this library, however I want to use it with an object that extends a JFoenix class (specifically, RecursiveTreeObject<T>). If I try to use it now I get a StackOverflowError. If it eventually supported this I would definitely use it heavily for a very large project. Any chance we could see this functionality added? It's also possible I'm doing it incorrectly, but it works fine serializing with normal Gson.

**Comment by joffrey-bion** [comment] 2016-11-02 22:59
Hi, thanks for letting me know.

I didn't know about JFoenix, I'll look into this `RecursiveTreeObject<T>` class. If you have any additional details about the issue feel free to comment here.
It looks like there is some recursive reference here, and I'm surprised that Gson manages to serialize it. There must be some `Property` field in that class that FxGson doesn't like. I'll sure take a look.

**Comment by robotStepheny** [comment] 2016-11-02 23:10
Conveniently, their demo src has almost the same Person example you use on your docs. If you look at the bottom of the file, you'll see the class extending the JFoenix class. This is the exact context I want to use it. Thanks for taking a look and for your awesome library. :)

https://github.com/jfoenixadmin/JFoenix/blob/9e12c478a880de9a8a5450947f6670d340395794/demo/demos/gui/uicomponents/TreeTableViewController.java

**Comment by joffrey-bion** [comment] 2016-11-02 23:22
Ok, thanks for the additional link, this may be helpful. I confirmed here that the vanilla Gson doesn't reach StackOverflowError. Now I'll dig a bit more to understand why FxGson does, and find a fix.

That being said, it looks like you will be disappointed by the serialized result even after the fix, as there will be the `RecursiveTreeObject` internal fields serialized along along your class's fields.
If you indeed don't want these extra fields serialized, you might want to write a custom `TypeAdapter` for your class anyway, which will make use of FxGson type adapters as delegates for your class's properties.

**Comment by joffrey-bion** [comment] 2016-11-03 00:05
Narrowed it down to the type `TreeTableColumn<T, ?>`. The `RecursiveTreeObject` class contains an `ObjectProperty<TreeTableColumn<T, ?>>` that's causing the problem.

I could reproduce the issue with this simple snippet:

    Gson gson = FxGson.create();
    String json = gson.toJson(new TreeTableColumn<>());

**Comment by robotStepheny** [comment] 2016-11-03 14:30
Thanks for the information, I will definitely look into writing my own TypeAdapter. Also it's worth nothing that Gson could not deserialize the class (which surprised me because it serialized as expected), at least from my small test. So this may be outside of the scope of your library.

**Comment by joffrey-bion** [comment] 2016-11-03 16:45
Yes, I believe the `RecursiveTreeObject` is more of UI element that is not really meant to be serialized.

I'm not familiar to JFoenix, and to why/how they merged model classes with UI elements. However, correct me if I'm wrong, but I believe that in your case, what you want is to only serialize `Person`'s fields, and you're not really concerned about the internals of the parent class.

I'll soon update the doc to explain how to make your own `TypeAdapter` while still making use of FxGson's built-in adapters for your properties.

**Closed** 2017-02-06 19:22 UTC

**Comment by joffrey-bion** [comment] 2017-02-07 00:21
FYI, one way to avoid serializing/deserializing some particular problematic classes such as `TreeTableColumn` is to use Gson's `ExclusionStrategy`:

```java
ExclusionStrategy strategy = new ExclusionStrategy() {
    @Override
    public boolean shouldSkipField(FieldAttributes f) {
        return false;
    }

    @Override
    public boolean shouldSkipClass(Class<?> clazz) {
        return clazz == TreeTableColumn.class;
    }
};
Gson gson = FxGson.coreBuilder()
                  .addSerializationExclusionStrategy(strategy)
                  .addDeserializationExclusionStrategy(strategy)
                  .create();
```

**Comment by skorper** [comment] 2017-02-08 23:22
Awesome, thanks a lot @joffrey-bion :)
